apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-checker-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-checker
subjects:
- kind: ServiceAccount
  name: pod-checker-sa
  namespace: default