apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook
webhooks:
  - name: validate.default.svc
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1"]
    objectSelector:
      matchLabels:
        type: my-pod-value  
    rules:
      - apiGroups: ["apps", ""]
        resources:          
          - "pods"
        apiVersions:
          - "*"
        operations:
          - CREATE
        scope: "Namespaced"
    clientConfig:
      service:
        name: validate
        namespace: default
        path: /validate/
      caBundle: <caBundle>
